name: Python test (utilities)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Pip dependencies
        run: pip install -r utils/requirements.txt
      - name: Run tests
        run: make test_python
